// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhmxbfxwayfkexnwphpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpobXhiZnh3YXlma2V4bndwaHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MTIxNjgsImV4cCI6MjA2MTQ4ODE2OH0.uN2JemovB1J-bwRVE-4FXHl1gZnZ-KHAp3_u_mgZrQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);